import { Fragment, useState } from 'react';
import { Link } from 'react-router-dom';
import { Handshake, HandHeart, Heartbeat, Hospital } from '@phosphor-icons/react';
import { api } from '../api';
import { useResource, useAsync, Notice, Loading, Empty, PageHeading, Status, Stats, SearchBox, ConfirmButton, ScoreBreakdown, FlagList, formatDate, formatDateTime } from '../components';

const TABS = ['hospitals', 'members', 'requests', 'pledges', 'matches', 'records', 'audit'];

function RecipientRanking({ pledgeId }) {
  const resource = useResource(`/admin/pledges/${pledgeId}/recipients`);
  if (resource.loading) return <Loading />;
  if (resource.error) return <Notice>{resource.error}</Notice>;
  const { recipients, notice, flags } = resource.data;
  return <div className="ranking">{notice && <p className="rank-note warn">{notice}</p>}<FlagList flags={flags} />{recipients.length ? <ol className="ranking-list">{recipients.map((r) => <li key={r.request_id} className="candidate"><div><span className="eyebrow">#{r.rank} · Request #{r.request_id}</span><h3>{r.organ} · {r.blood_group} <span className="muted">({r.blood_match.replace('-', ' ')})</span></h3><div className="candidate-meta"><span>{r.hospital_name}, {r.city}</span><span>Priority <Status value={r.priority} /></span><span>Patient age {r.patient_age ?? '—'}</span><span>Verified {formatDate(r.verified_at)}</span></div></div><ScoreBreakdown score={r.score} breakdown={r.breakdown} /></li>)}</ol> : !notice && <Empty title="No eligible recipients">No verified open request can receive this pledge right now.</Empty>}</div>;
}

export function Admin() {
  const resource = useResource('/admin/dashboard'); const [tab, setTab] = useState('hospitals'); const [search, setSearch] = useState(''); const action = useAsync(); const [ranking, setRanking] = useState(null);
  const data = resource.data;
  const find = (rows, ...fields) => rows.filter((row) => fields.map((field) => row[field] ?? '').join(' ').toLowerCase().includes(search.toLowerCase()));
  const act = (fn) => action.run(async () => { await fn(); resource.refresh(); });
  const table = (head, rows, empty) => rows.length ? <div className="table-wrap"><table><thead><tr>{head.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows}</tbody></table></div> : <Empty title={empty}>Try a different search.</Empty>;
  return <div className="page-container workspace"><PageHeading eyebrow="National coordination" title="Care starts with coordination.">Verify hospitals, oversee priority matching, and review every decision on the record.</PageHeading><Notice>{resource.error || action.error}</Notice>{resource.loading && !data ? <Loading /> : data && <>
    <Stats items={[['Hospitals awaiting verification', data.hospitals.filter((h) => h.status === 'pending').length, Hospital], ['Verified open requests', data.requests.filter((r) => r.status === 'open' && r.verification === 'verified').length, Heartbeat], ['Active pledges', data.pledges.filter((p) => p.status === 'active').length, HandHeart], ['Active matches', data.matches.filter((m) => ['proposed', 'confirmed'].includes(m.status)).length, Handshake]]} />
    <div className="admin-toolbar"><div className="tabs" role="group" aria-label="Administration view">{TABS.map((name) => <button key={name} aria-pressed={tab === name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name[0].toUpperCase() + name.slice(1)}</button>)}</div><SearchBox value={search} onChange={setSearch} placeholder="Search this tab" /></div>
    {tab === 'hospitals' && table(['Hospital', 'Location', 'Contact', 'Requests', 'Status', 'Action'], find(data.hospitals, 'name', 'registration_number', 'city', 'state', 'email').map((h) => <tr key={h.id}><td><strong>{h.name}</strong><small>{h.registration_number} · joined {formatDate(h.created_at)}</small></td><td>{h.city}, {h.state} {h.pincode}</td><td>{h.email}<small>{h.phone}</small></td><td>{h.request_count}</td><td><Status value={h.status} /></td><td>{h.status !== 'verified' ? <button className="text-button" disabled={action.busy} onClick={() => act(() => api(`/admin/hospitals/${h.id}`, { method: 'PATCH', body: { status: 'verified' } }))}>{h.status === 'suspended' ? 'Reinstate' : 'Verify'}</button> : <ConfirmButton confirmLabel="Suspend hospital" busyLabel="Suspending…" description={`Suspend ${h.name}? Its staff lose portal access and its requests leave priority matching.`} onConfirm={async () => { await api(`/admin/hospitals/${h.id}`, { method: 'PATCH', body: { status: 'suspended' } }); resource.refresh(); }}>Suspend</ConfirmButton>}</td></tr>), 'No matching hospitals')}
    {tab === 'members' && table(['Account', 'Email', 'Role', 'Blood group', 'Phone', 'Joined', 'Action'], find(data.users, 'first_name', 'last_name', 'email', 'role', 'hospital_name').map((u) => <tr key={u.id}><td><strong>{u.first_name} {u.last_name}</strong>{u.hospital_name && <small>{u.hospital_name}</small>}</td><td>{u.email}</td><td>{u.role}</td><td>{u.blood_group || '—'}</td><td>{u.phone}</td><td>{formatDate(u.created_at)}</td><td>{u.role !== 'admin' ? <ConfirmButton description={`Delete ${u.first_name}'s account and all their requests, pledges, and records?`} onConfirm={async () => { await api(`/admin/users/${u.id}`, { method: 'DELETE' }); resource.refresh(); }} /> : '—'}</td></tr>), 'No matching accounts')}
    {tab === 'requests' && table(['Member', 'Organ', 'Blood group', 'Hospital', 'Verification', 'Priority', 'Status', 'Action'], find(data.requests, 'first_name', 'last_name', 'organ', 'hospital_name').map((r) => <tr key={r.id}><td>{r.first_name} {r.last_name}<small>#{r.id}</small></td><td><strong>{r.organ}</strong></td><td>{r.blood_group}</td><td>{r.hospital_name || '—'}</td><td><Status value={r.verification} /></td><td>{r.priority ? <Status value={r.priority} /> : '—'}</td><td><Status value={r.status} /></td><td><Link className="text-link" to={`/requests/${r.id}/edit`}>Edit</Link> <button className="text-button" disabled={action.busy} onClick={() => act(() => api(`/requests/${r.id}`, { method: 'PATCH', body: { status: r.status === 'open' ? 'closed' : 'open' } }))}>{r.status === 'open' ? 'Close' : 'Reopen'}</button></td></tr>), 'No matching requests')}
    {tab === 'pledges' && table(['Donor', 'Organ', 'Donation', 'Location', 'Status', 'Pledged', 'Ranking'], find(data.pledges, 'first_name', 'last_name', 'organ', 'city', 'state').map((p) => <Fragment key={p.id}><tr><td>{p.first_name} {p.last_name}<small>Pledge #{p.id} · {p.blood_group}</small></td><td><strong>{p.organ}</strong></td><td><Status value={p.donor_type} /></td><td>{p.city}, {p.state}</td><td><Status value={p.status} />{p.available_at && <small>Available at {p.available_hospital_name}</small>}</td><td>{formatDate(p.created_at)}</td><td><button className="text-button" aria-expanded={ranking === p.id} onClick={() => setRanking(ranking === p.id ? null : p.id)}>{ranking === p.id ? 'Hide' : 'Recipients'}</button></td></tr>{ranking === p.id && <tr className="ranking-row"><td colSpan={7}><RecipientRanking pledgeId={p.id} /></td></tr>}</Fragment>), 'No matching pledges')}
    {tab === 'matches' && table(['Match', 'Organ', 'Hospital', 'Recipient', 'Donor', 'Score / rank', 'Donor response', 'Status'], find(data.matches, 'organ', 'hospital_name', 'requester_first_name', 'requester_last_name', 'donor_first_name', 'donor_last_name').map((m) => <tr key={m.id}><td>#{m.id}<small>{formatDate(m.created_at)}</small></td><td><strong>{m.organ}</strong></td><td>{m.hospital_name}</td><td>{m.requester_first_name} {m.requester_last_name}</td><td>{m.donor_first_name} {m.donor_last_name}</td><td>{m.score} · #{m.recipient_rank}{m.override_reason && <small>Override: {m.override_reason}</small>}</td><td><Status value={m.donor_response} /></td><td><Status value={m.status} />{m.decision_reason && <small>{m.decision_reason}</small>}</td></tr>), 'No matches yet')}
    {tab === 'records' && table(['Member', 'Organ', 'Blood group', 'Quantity', 'Donation date', 'Note'], find(data.records, 'first_name', 'last_name', 'organ').map((r) => <tr key={r.id}><td>{r.first_name} {r.last_name}</td><td><strong>{r.organ}</strong></td><td>{r.blood_group}</td><td>{r.quantity}</td><td>{formatDate(r.donated_on)}</td><td className="table-note">{r.note || '—'}</td></tr>), 'No donation records yet')}
    {tab === 'audit' && table(['When', 'Actor', 'Action', 'Record', 'Details'], find(data.events, 'first_name', 'last_name', 'action', 'entity').map((e) => <tr key={e.id}><td>{formatDateTime(e.created_at)}</td><td>{e.first_name ? `${e.first_name} ${e.last_name}` : 'Deleted account'}<small>{e.role}</small></td><td>{e.action.replaceAll('_', ' ')}</td><td>{e.entity} #{e.entity_id}</td><td className="table-note"><code>{JSON.stringify(e.detail)}</code></td></tr>), 'No audit events yet')}
  </>}</div>;
}
